name: Azure VM-DevOps - New Machines

on:
  push:
    branches:
      - main

jobs:
  deploy-new-machines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          host: ['${ secrets.SSH_HOST }' , '${ secrets.SSH_HOST_2 }']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy project on New VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.host }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "installing python3-pip, python3"
          sudo apt update
          sudo apt install -y python3-pip python3
          if [ ! -d "$HOME/HAproxy" ]; then
            echo "Directory HAproxy doesn't exist, cloning directory"
            git clone https://yahavg10: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@github.com/yahavg10/HAproxy.git
          fi
          echo "changing to repo directory"
          cd $HOME/HAproxy
          echo "installing dependencies from requirements.txt"
          pip install -r requirements.txt
          echo "copying service config"
          sudo cp log_images_http_server.service /etc/systemd/system/
          echo "reloading system configurations"
          sudo systemctl daemon-reload
          echo "starting service"
          sudo systemctl restart log_images_http_server
